In [2]:
import sys

print(sys.executable)

/opt/homebrew/opt/python@3.12/bin/python3.12


In [3]:
import numpy as np

np.__version__

'2.1.1'

zsh:1: command not found: pip


# The Basics of NumPy Arrays

## NumPy Array Attributes

In [5]:
import numpy as np

rng = np.random.default_rng(seed=10)

x1 = rng.integers(10, size=6)  # one-dim array
x2 = rng.integers(10, size=(3, 4))  # two-dim array
x3 = rng.integers(10, size=(4, 6, 8))  # three-dim array

In [6]:
print("x3 ndim : ", x3.ndim)
print("x3 shape : ", x3.shape)
print("x3 size : ", x3.size)
print("x3 dtype: ", x3.dtype)

x3 ndim :  3
x3 shape :  (4, 6, 8)
x3 size :  192
x3 dtype:  int64


## Array Indexing: Accessing Single Elements

In [7]:
x1

array([7, 9, 2, 2, 7, 8])

In [8]:
x1[0]

np.int64(7)

In [9]:
x1[4]

np.int64(7)

In [10]:
# To index from the end of the array, you can use negative indices:

x1[-1]

np.int64(8)

In [11]:
x1[-4]

np.int64(2)

In [12]:
x1[-10]

IndexError: index -10 is out of bounds for axis 0 with size 6

In a multidimensional array, items can be accessed using a comma-separated [row, column] tuple:

In [13]:
x2

array([[5, 1, 8, 5],
       [1, 1, 4, 6],
       [4, 8, 0, 4]])

In [14]:
x2[0, 0]

np.int64(5)

In [15]:
x2[2, 0]

np.int64(4)

In [16]:
x2[1, -1]

np.int64(6)

In [18]:
x2[2, -1] = 12

x2

array([[ 5,  1,  8,  5],
       [ 1,  1,  4,  6],
       [ 4,  8,  0, 12]])

unlike Python lists, NumPy arrays have a fixed type. This means, for example, that if you attempt to insert a floating-point value into an integer array, the value will be silently truncated

In [20]:
print(x1)
x1[0] = 3.675
print(x1)

[7 9 2 2 7 8]
[3 9 2 2 7 8]


## Array Slicing: Accessing Subarrays

### One dimensional sub array

In [21]:
x1

array([3, 9, 2, 2, 7, 8])

In [22]:
# first 3 elements
x1[:3]

array([3, 9, 2])

In [23]:
# all elements from 3rd position
x1[3:]

array([2, 7, 8])

In [24]:
# middle sub-array
x1[2:5]

array([2, 2, 7])

In [25]:
# every second element
x1[::2]

array([3, 2, 7])

In [26]:
# every second element starting at index 1
x1[1::2]

array([9, 2, 8])

In [27]:
# all elements reversed
x1[::-1]

array([8, 7, 2, 2, 9, 3])

In [28]:
# every second element from index 3 reversed

x1[3::-2]

array([2, 9])

In [29]:
x1[4::-2]

array([7, 2, 3])

### Multi dimensional subarrays

In [30]:
x2

array([[ 5,  1,  8,  5],
       [ 1,  1,  4,  6],
       [ 4,  8,  0, 12]])

In [31]:
x2[1, 0] = 3
x2[0, 1] = 7
x2[2, 1] = 15
x2[1, 2] = 9

x2

array([[ 5,  7,  8,  5],
       [ 3,  1,  9,  6],
       [ 4, 15,  0, 12]])

In [32]:
# first 2 rows and 3 columns
x2[:2, :3]

array([[5, 7, 8],
       [3, 1, 9]])

In [33]:
# first 3 rows and every second column
x2[:3, ::2]

array([[5, 8],
       [3, 9],
       [4, 0]])

In [34]:
# all rows and columns reversed
x2[::-1, ::-1]

array([[12,  0, 15,  4],
       [ 6,  9,  1,  3],
       [ 5,  8,  7,  5]])

### Accessing array rows and columns

In [35]:
# first column of x2
x2[:, 0]

array([5, 3, 4])

In [36]:
# first row of x2

x2[0, :]

array([5, 7, 8, 5])

In [37]:
# same as above
x2[0]

array([5, 7, 8, 5])

In [38]:
# cant do that for the columns
x2[,0]

SyntaxError: invalid syntax (311118697.py, line 2)

### Subarrays as No-Copy Views

Unlike Python list slices, NumPy array slices are returned as views rather than copies of the array data. Consider our two-dimensional array from before:

In [39]:
print(x2)

[[ 5  7  8  5]
 [ 3  1  9  6]
 [ 4 15  0 12]]


In [40]:
# lets extract a 2X2 subarray from this

x2_sub = x2[:2, :2]
print(x2_sub)

[[5 7]
 [3 1]]


In [41]:
# Now if we modify this subarray, we'll see that the original array is changed! Observe:
x2_sub[0, 0] = 99

print(x2_sub)

print(x2)

[[99  7]
 [ 3  1]]
[[99  7  8  5]
 [ 3  1  9  6]
 [ 4 15  0 12]]


### Creating Copies of Arrays
Despite the nice features of array views, it is sometimes useful to instead explicitly copy the data within an array or a subarray. This can be most easily done with the copy method:


In [42]:
x2_sub_copy = x2[:2, :2].copy()

print(x2_sub_copy)

[[99  7]
 [ 3  1]]


In [43]:
# if we now modify the copy subsarray, the original is not changed

x2_sub_copy[0, 0] = 33
print(x2_sub_copy)

print(x2)

[[33  7]
 [ 3  1]]
[[99  7  8  5]
 [ 3  1  9  6]
 [ 4 15  0 12]]


## Reshaping of Arrays

Another useful type of operation is reshaping of arrays, which can be done with the reshape method. For example, if you want to put the numbers 1 through 9 in a 
 grid, you can do the following:

In [44]:
grid = np.arange(1, 10).reshape(3, 3)
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [45]:
# row vector via reshape

x = np.array([1, 2, 3])

x.reshape((1, 3))

array([[1, 2, 3]])

In [50]:
y = x.reshape((1, 3))

y[:, :2]

array([[1, 2]])

In [52]:
# row vector via newaxis
y1 = x[np.newaxis, :]
y1

array([[1, 2, 3]])

In [51]:
z = x.reshape((3, 1))  # column vector

z[:2, :]

array([[1],
       [2]])

In [53]:
# column vector via newaxis

z1 = x[:, np.newaxis]

z1

array([[1],
       [2],
       [3]])

## Array Concatenation and Splitting

All of the preceding routines worked on single arrays. NumPy also provides tools to combine multiple arrays into one, and to conversely split a single array into multiple arrays.


### Concatenation of Arrays
Concatenation, or joining of two arrays in NumPy, is primarily accomplished using the routines np.concatenate, np.vstack, and np.hstack. np.concatenate takes a tuple or list of arrays as its first argument, as you can see here: